config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'posts/index'
  get '/users/:id/posts', to: 'posts#user_index', as: 'user_posts'

  resources :posts do
    patch :vote, on: :member
  end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, inverse_of: :posts
  has_many :votes, dependent: :destroy, inverse_of: :post
  delegate :email, to: :user

  validates :title, presence: true
  validates :text, presence: true

  scope :foremost, -> { order('rating DESC, created_at DESC') }

  def moderate?(user)
    self.user_id == user.try(:id)
  end

  def vote(user)
    if vote = votes.find_by(user_id: user.id)
      vote.destroy
    else
      votes.create(user_id: user_id)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts, dependent: :destroy, inverse_of: :user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post, counter_cache: :rating, inverse_of: :votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  VOTES = :votes

  before_action :authenticate_user!, except: [:index, :show, :vote]
  before_action :find_user, only: [:user_index]
  before_action :find_post, only: [:show, :vote]
  before_action :find_own_post, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @posts = Post.foremost
  end

  def user_index
    @posts = @user.posts.foremost
    render 'index'
  end

  def new
    @post = Post.new
  end

  def create
    if current_user.posts.create(post_params)
      redirect_to posts_path, notice: 'Post was created'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path
    else 
      redirect_to edit_post_path(@post)
    end
  end

  def vote
    if user_signed_in?
      @post.vote(current_user)
    else
      vote_cookies
    end 
  end

  private
  def vote_cookies
    votes = (cookies[VOTES] || '').split(',')
    existing_vote_id = @post.votes.find_by(id: votes)
    if existing_vote_id
      @post.votes.destroy(existing_vote_id)
      votes.delete(existing_vote_id)
    else
      votes.push(@post.votes.create.id)
    end
    cookies[VOTES] = votes.join(',')
  end
  
  def find_user
    @user = User.find(params[:id])
  end 

  def find_own_post
    @post = current_user.posts.find(params[:id])
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RafaelsNewsStand</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header container">
    <div class="blog-header">
      <h1 class="blog-title">Rafael's news stand</h1>
      <p class="lead blog-description">Simple rails app</p>
      <% if user_signed_in? %>
        <p align="center">
          <strong><%= link_to 'New post', new_post_path %></strong>
          ·
          <strong><%= link_to 'My posts', user_posts_path(current_user) %></strong>
          ·
          <strong><%= link_to 'All posts', posts_path %></strong>
        </p>
      <% end %>
    </div>
    <div class="blog-navigation pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>
        &nbsp;
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default' %>
      <% else %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default' %>
        <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :text %>
  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/posts/_post.html.erb
<h2 class="blog-post-title"><%= post.title %></h2>
<p class="blog-post-meta"><%= I18n.l(post.created_at, format: :short) %> by <a href="#"><%= post.email %></a></p>
<p><%= post.text %></p>
<p>
  <%= link_to vote_post_path(post), method: :patch, remote: true do %>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
  <% end %>
  <span id="<%= dom_id(post, :rating)%>"><%= post.votes.count %></span>
</p>

app/views/posts/edit.html.erb
<h3>Edit Post</h3>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if @posts.count > 0 %>
  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-sm-12 blog-main">
        <div class="blog-post">
          <%= render post %>
          <p>
            <% if post.moderate?(current_user) %>
              <%= link_to 'Show', post_path(post)%>,
              <%= link_to 'Edit', edit_post_path(post) %>,
              <%= link_to 'Delete', post_path(post),
                method: :delete,
                data: { confirm: 'Are you sure?' }
              %>
            <% else %>
              <%= link_to 'Show', post_path(post)%>
            <% end %>
          <p>
          <hr>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row">
    <h2>No posts yet..</h2>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <h3>New Post</h1>
  <%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'To news page', posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>

<% if @post.moderate?(current_user) %>
  <p>
    <%= link_to 'Edit', edit_post_path(@post) %>, 
    <%= link_to 'Delete', post_path(@post),
      method: :delete,
      data: { confirm: 'Are you sure?' } 
    %>
  </p>
<% end %>
<p><%= link_to 'Back', posts_path %></p>

app/views/posts/vote.js.erb
$("#<%= dom_id(@post, :rating)%> ").html("<%= @post.votes.count %>");

app/views/posts/vote_up.js.erb
$("#<%= @post.id%>.rating-value").html("<%= @post.votes.count %>");

/*
$("#<%= @post.id%>.rating-button").click(function() {
  $.ajax("/posts/<%= @post.id%>/vote_up")
  $("#<%= @post.id%>.rating-value").html('<%= @post.votes.count %>')
});
*/